# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='例句表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('漢字', models.CharField(max_length=255)),
                ('臺羅', models.CharField(max_length=255)),
                ('華語', models.CharField(max_length=255)),
                ('分詞', models.CharField(max_length=1000)),
            ],
        ),
    ]
